### ISSUE TITLE
Doesn't build on Windows (64bit, but 32bit compiler) due to RDRAND

### ISSUE THREAD

**Issue by neongreen** [TomMD/entropy#25]
If I understand correctly, when the compiler is 32bit, `rdrand.c` doesn't get included, but RDRAND support is still being detected by the setup script and code behaves as if `rdrand.c` is present, which results in a broken package.

**Comment by TomMD** [comment]
Could you copy and paste the actual error message?

**Comment by TomMD** [comment]
Nevermind, it looks like I've allowed the windows support to lag a little.  I'll get it.
