### ISSUE TITLE
Linking error "In function `get_rand_bytes': undefined reference to `_rdrand64_step'"

### ISSUE THREAD

**Issue by vlatkoB** [TomMD/entropy#27]
Hi,

I'm trying to compile `clientsession` and on linking stage I get three errors
```
Linking dist/dist-sandbox-2803e1ed/build/clientsession-generate/clientsession-generate ...
.../.stackage/sandboxes/ghc-7.8.4/lts-2.14/lib/x86_64-linux-ghc-7.8.4/entropy-0.3.6/libHSentropy-0.3.6.a(rdrand.o): In function `get_rand_bytes':
(.text+0x6c): undefined reference to `_rdrand64_step'
.../.stackage/sandboxes/ghc-7.8.4/lts-2.14/lib/x86_64-linux-ghc-7.8.4/entropy-0.3.6/libHSentropy-0.3.6.a(rdrand.o): In function `get_rand_bytes':
(.text+0xba): undefined reference to `_rdrand64_step'
.../.stackage/sandboxes/ghc-7.8.4/lts-2.14/lib/x86_64-linux-ghc-7.8.4/entropy-0.3.6/libHSentropy-0.3.6.a(rdrand.o): In function `get_rand_bytes':
(.text+0xee): undefined reference to `_rdrand64_step'
```
I'm on `Arch` and using `LTS 2.14` config, GHC `7.8.4`.

Am I missing a library?

Best regards,

vlatko

**Comment by TomMD** [comment]
There should never be a `_random64_step` symbol because that function is inlined in `get_rand_bytes`.  See the `cbits/rdrand.c` file if you're curious.  What C compiler is this?  My first thought is this is a buggy compiler, bu tI could be missing something.

**Comment by TomMD** [comment]
Some testing shows clang with -O less than 2 yields object code with the step function undefined.  So I am guessing you are using clang and, for some reason, `ghc -O2` does not invoke clang with `-ON` where `N >= 2`.  Sound right?   Either way, I suspect the solution is to add `-O2` to the `cc-options:` field of `entropy.cabal`.  If this works for you then let me know and I'll upload a patched version.

**Comment by TomMD** [comment]
Upstream bug filed: https://llvm.org/bugs/show_bug.cgi?id=23850

**Comment by vlatkoB** [comment]
Wow, aren't you a fast one. :-) 
All fine now. Thanks.

BTW, I do not have clang installed. Have base-devel (cc and gcc).

**Comment by TomMD** [comment]
@vlatkoB Yes, I had a misunderstanding about C99 (vs Gnu89) `inline` keyword which resulted in many compilers producing bad code when ran without optimizations.  I think not optimizing is itself a bug for cabal, but am satisfied enough with how things are working now.

Thank you for the bug report!
