### ISSUE TITLE
System.Posix.IO vs System.IO

### ISSUE THREAD

**Issue by redneb** [TomMD/entropy#29]
I noticed that in `System/EntropyNix.hs` you are using the I/O functions from `System.Posix.IO` instead of the ones from `System.IO`. Is there a reason for that? The disadvantage of this approach is that e.g. `fdReadBuf` is implemented using a safe foreign import which has significant overhead compared to `hGetBuf` from `System.IO` which should be faster.

An additional small benefit is that by using `System.IO` you can get rid of the `unix` dependency.

**Comment by TomMD** [comment]
The use of POSIX is from pull request #4 for QNX support.  If this causes anyone build issues I can make a EntropyQnx separate from EntropyNix.   Just let me know.
