### ISSUE TITLE
Consider getentropy/getrandom on supported platforms

### ISSUE THREAD

**Issue by Ongy** [TomMD/entropy#31]
For platforms that support it, getentropy should be used.
Reading from `/dev/urandom` will provide us with random data, but the file interface has a lot of ways to fail. The syscalls have less ways they fail in and, as the manpage says, behave better with interrupts.

On linux the syscall is called `getrandom`, the man page has a section on emulating getentropy.

http://man7.org/linux/man-pages/man2/getrandom.2.html

**Comment by TomMD** [comment]
I'd like to see this done but `getrandom` still isn't available on most systems I use (glibc is too old) and I don't know of a good way to do the compile time check for `getrandom`. 

Off the cuff, I'm thinking I should create a package that can test for `getrandom` in a manner similar to the `aes-ni` tests I currently have.  Those packages could then be entered in the `build-tool-depenciencies` (I think, need to check the semantics here) so I can make a simpiler `Setup.lhs`.
