### ISSUE TITLE
entropy.cabal needs a setup-depends field i think?

### ISSUE THREAD

**Issue by cartazio** [TomMD/entropy#32]
https://travis-ci.org/cartazio/random/jobs/234589847 is some debugging i'm hitting

maybe @hvr or @ryanglscott can help?

**Comment by cartazio** [comment]
herbert did a fix up revision http://hackage.haskell.org/package/entropy-0.3.7/revisions/
would be good to update the git version :)

**Comment by cartazio** [comment]
my random builds now build https://travis-ci.org/cartazio/random/builds/234606771 :)

**Comment by hvr** [comment]
@TomMD if you have any questions re cabal & `setup-depends`, please feel free to ask!

**Comment by TomMD** [comment]
@hvr @cartazio Yep, updated to the way of things now. Thanks for the changes hvr.
