### ISSUE TITLE
Failed to install entropy-0.3.8 | ArchLinux

### ISSUE THREAD

**Issue by rapofran** [TomMD/entropy#34]
Hi Tom, I'm a very newbie user of Haskell and Arch but when I run `cabal install entropy-0.3.8` I'm getting this error:

```
entropy-0.3.8 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
/usr/bin/ld: cannot find -lHSCabal-1.24.2.0
/usr/bin/ld: cannot find -lHSprocess-1.4.3.0
/usr/bin/ld: cannot find -lHSpretty-1.1.3.3
/usr/bin/ld: cannot find -lHSdirectory-1.3.0.0
/usr/bin/ld: cannot find -lHSunix-2.7.2.1
/usr/bin/ld: cannot find -lHStime-1.6.0.1
/usr/bin/ld: cannot find -lHSfilepath-1.4.1.1
/usr/bin/ld: cannot find -lHSbinary-0.8.3.0
/usr/bin/ld: cannot find -lHScontainers-0.5.7.1
/usr/bin/ld: cannot find -lHSbytestring-0.10.8.1
/usr/bin/ld: cannot find -lHSdeepseq-1.4.2.0
/usr/bin/ld: cannot find -lHSarray-0.5.1.1
/usr/bin/ld: cannot find -lHSbase-4.9.1.0
/usr/bin/ld: cannot find -lHSinteger-gmp-1.0.0.1
/usr/bin/ld: cannot find -lHSghc-prim-0.5.0.0
/usr/bin/ld: cannot find -lHSrts_thr
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
)
```

I put all the output here https://gist.github.com/rapofran/4348799a64570e9fc047a0e738ecef9c

```
cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library
```
`gcc --version => gcc (GCC) 7.1.1 20170516`
`ghc --version => The Glorious Glasgow Haskell Compilation System, version 8.0.2`
```
uname -a
Linux arch-dell 4.9.33-1-MANJARO #1 SMP PREEMPT Sat Jun 17 14:07:44 UTC 2017 x86_64 GNU/Linux
```

What am I doing wrong? I'm sure there is something missing on my setup

Thanks a lot,
Frank

**Comment by TomMD** [comment]
This is a tooling issue with your GHC installation. I recall seeing something similar WRT Arch and it's packaging of shared libraries recently, but can't recall where.  Try to install a GHC binary from haskell.org/ghc.  If that fixes it then this ticket could be migrated to the Arch GHC packager.

**Comment by rapofran** [comment]
I resolved this installing `ghc-static`. As it says here https://wiki.archlinux.org/index.php/Haskell#Problems_with_linking

Thanks Tom
