### ISSUE TITLE
"failed to parse output of 'ghc-pkg dump'" with ghc-8.4 alpha3

### ISSUE THREAD

**Issue by DanBurton** [TomMD/entropy#37]
I'm not sure what changed or how stable the current format is, but I figured I'd send the report anyways in case it's useful.

**Comment by TomMD** [comment]
Hurm, thanks for the heads up.  I'll have to get a ghc-8.4 rc and try things out before or soon after release.

**Comment by DanBurton** [comment]
Bump, I'm seeing the same failure with ghc-8.4.1-rc1.

**Comment by TomMD** [comment]
In my best Bilbo voice 

> I've put this off for far too long.

It appears time has gotten away from me - I'm looking at this now, just a couple weeks late.

**Comment by TomMD** [comment]
I can not reproduce your issue in particular.  I can successfully cabal-install the package but admit `cabal new-build` has some objections about the version of cabal if I don't use `--allow-newer`.

Did your bug disappear with GHC-8.4.1 vs alpha3?

**Comment by DanBurton** [comment]
Yep. I tried with the released ghc-8.4.1 and the bug disappeared. ¯\\\_(ツ)_/¯
