### ISSUE TITLE
Setup.hs foils cross-compilation

### ISSUE THREAD

**Issue by ariep** [TomMD/entropy#42]
`entropy` currently uses a custom `Setup.hs` to decide whether it can use RDRAND. This means that it cannot be cross-compiled.

From the comments in the cabal file I conclude that it's not possible to make the `build-type` depend on a flag, is that correct? Having a flag to override this behaviour would help.

Currently the workaround is to locally modify this package (to have `build-type: Simple`), but that's rather inconvenient.

**Comment by TomMD** [comment]
I agree it is inconvenient.  Is there any "cross compilation" flag in cabal's build info?  If so we could "do the right thing" inside of Setup.hs.
