### ISSUE TITLE
Use terminfo-hs instead of terminfo where reliable?

### ISSUE THREAD

**Issue by no-identd** [TomMD/entropy#44]
See https://github.com/commercialhaskell/stack/issues/1137 for the report from @mrLSD, and see https://github.com/jtdaugherty/vty/issues/82 for a similar issue.

You might also want to know that terminfo seems to suffer from some licensing inconsistency:

https://github.com/judah/terminfo/issues/6

**Comment by TomMD** [comment]
Could you say more?  It is not clear to me how terminfo has anything to do with this package.

**Comment by no-identd** [comment]
...I think I might have made a mistake here. Nevermind. :)
